FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Expose port
EXPOSE 4000

# Start server
CMD ["node", "index.js"]
